# Generated by Django 5.1.4 on 2025-01-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_maximum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='device_minimum',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
