# Generated by Django 5.1.4 on 2025-01-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_device_maximum_device_device_minimum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=50, null=True),
        ),
    ]
