# Generated by Django 5.1.4 on 2025-01-23 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_device_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_maximum',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_minimum',
        ),
    ]
