# Generated by Django 5.1.4 on 2025-01-23 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_remove_device_device_maximum_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicedata',
            old_name='type',
            new_name='data_type',
        ),
    ]
